services:
  neo4j_cross:
    image: neo4j:5.12
    container_name: neo4j_cross
    ports:
      - "7474:7474" 
      - "7687:7687" 
    environment:
      - NEO4J_AUTH=neo4j/password  
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.meta.data,apoc.*
    volumes:
      - neo4j_cross_data:/data
      - neo4j_cross_logs:/logs
      # - neo4j_config:/config
      - neo4j_cross_plugin:/plugins
  
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma_service
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
      - CHROMA_SERVER_CORS_ALLOW_CREDENTIALS=true
    volumes:
      - chroma_data:/chroma/chroma

  python-app:
    build:
      context: .  
    container_name: python-app
    env_file:
      - .env
    depends_on:
      - chroma
      - neo4j_cross
    environment:
      - API_KEY=${API_KEY}
      - TOKENIZERS_PARALLELISM=false
      - CHROMA_HOST=chroma
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./professor_images:/app/professor_images
    ports:
      - "8008:8008"

volumes:
  neo4j_cross_data:
  neo4j_cross_logs:
  neo4j_cross_plugin:
  chroma_data:
