
services:
  neo4j_cross:
    image: neo4j:5.12
    container_name: neo4j_cross
    ports:
      - "7474:7474" 
      - "7687:7687" 
    environment:
      - NEO4J_AUTH=neo4j/password  
    volumes:
      - neo4j_cross_data:/data
      - neo4j_cross_logs:/logs
      # - neo4j_config:/config
      - neo4j_cross_plugin:/plugins

  python-app:
    build:
      context: .  
    container_name: python-app
    depends_on:
      - neo4j_cross

    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${API_KEY}
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    # ports:
    #   - "8000:8000"  

volumes:
  neo4j_cross_data:
  neo4j_cross_logs:
  neo4j_cross_plugin: