
services:
  neo4j_cross:
    image: neo4j:5.12
    container_name: neo4j_cross
    ports:
      - "7474:7474" 
      - "7687:7687" 
    environment:
      - NEO4J_AUTH=neo4j/password  
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.meta.data,apoc.*
    volumes:
      - neo4j_cross_data:/data
      - neo4j_cross_logs:/logs
      # - neo4j_config:/config
      - neo4j_cross_plugin:/plugins
  
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma_service
    ports:
      - "8000:8000"

  python-app:
    build:
      context: .  
    container_name: python-app
    depends_on:
      - neo4j_cross
      - chroma
    env_file:
      - .env
    links:
      - chroma
    environment:
      - API_KEY=${API_KEY}
      - TOKENIZERS_PARALLELISM=false
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    ports:
      - "8008:8008"  

volumes:
  neo4j_cross_data:
  neo4j_cross_logs:
  neo4j_cross_plugin:
